apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: translate
  name: translate
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: translate
    spec:
      containers:
      - image: cloud-fundamentals_translate
        name: translate
        resources: {}
      restartPolicy: Always
status: {}
